name: Main
on:
  - pull_request # without merge conflicts
  - push # branch or tag

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        dc: [ dmd-latest, ldc-latest ]
        include:
          - { os: ubuntu-latest, dc: gdc-14 }
    name: ${{ matrix.os }}, ${{ matrix.dc }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      N: ${{ startsWith(matrix.os, 'macos') && '3' || '2' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.dc }}
          dub: latest
      # rdmd_test.d needs this
      - name: Set DMD to its basename without extension
        run: |
          val=$(basename "${DMD}")
          val=${val%.*}
          tee -a ${GITHUB_ENV} <<<"DMD=${val}"
      - name: Build
        run: make -j$N DMD=$DMD
      - name: Test
        run: make -j$N DMD=$DMD test
      - name: 'Windows: Build and test with MODEL=32'
        if: runner.os == 'Windows'
        run: make -j$N DMD=$DMD MODEL=32 all test
